# docker configuration - postgresql

services:
  db:
    image: postgres:16.2-alpine
    container_name: $DB_NAME
    restart: always

    environment:
      POSTGRES_USER: $DB_USER 
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"

    ports:
      - $DB_PORT:$DB_PORT

    volumes:
      - ./data:/var/lib/postgresql/data
